version: '3.4'

services:
  jaeger: 
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

# 5775 - UDP - agent - accept zipkin.thrift over compact thrift protocol (deprecated, use by legacy clients only)
# 6831 - UDP - agent - accept jaeger.thrift over compact thrift protocol
# 6832 - UDP - agent - accept jaeger.thrift over binary thrift protocol
# 5778 - HTTP - agent - serve configs
# 16686 - HTTP - query - serve frontend
# 14268 - HTTP - collector - accept jaeger.thrift directly from clients
# 14250 - HTTP - collector - accept moel.proto 
# 9411 - HTTP - collector - Zipkin compatible endpoint (optional)